spring:
  application:
    name: microservice-with-sb-department-service
  config:
    import: "optional:configserver:http://localhost:8088"

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
